server:
  port: 9090

spring:
  profiles:
    active: local   # default profile for local dev

---
# =====================
# Local Development
# =====================
spring:
  config:
    activate:
      on-profile: local

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 2020

  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=1000,expireAfterWrite=30m

---
# =====================
# Docker / Compose
# =====================
spring:
  config:
    activate:
      on-profile: docker

  datasource:
    url: jdbc:postgresql://postgres:5432/postgres
    username: postgres
    password: 2020

  cache:
    type: redis
    data:
      redis:
        host: redis
        port: 6379
        timeout: 60000

---
# =====================
# Common Settings (applies to all profiles)
# =====================
spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  level:
    org.springframework.cache: TRACE
    com.insurance.policy.insutech.service: DEBUG

springdoc:
  api-docs:
    path: /api-docs  # OpenAPI JSON
  swagger-ui:
    path: /swagger-ui.html  # Swagger UI
    enabled: true
