server:
  port: 8181

spring:
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://user-service:9090
          predicates:
            - Path=/api/users/**
        - id: policy-service
          uri: http://policy-service:9899
          predicates:
            - Path=/api/v1/policies/**
        - id: managed-policy-service
          uri: http://managed-policy-service:9092
          predicates:
            - Path=/api/managed-policies/**
