spring:
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins:
              - "http://localhost:3000"
            allowed-methods: "*"
            allowed-headers: "*"
            allow-credentials: true
      routes:
        - id: user-service
          uri: http://user-service:9899
          predicates:
            - Path=/api/users/**
        - id: policy-service
          uri: http://policy-service:9090
          predicates:
            - Path=/api/v1/policies/**
        - id: managed-policy-service
          uri: http://managed-policy-service:9092
          predicates:
            - Path=/api/managed-policies/**

  data:
    redis:
      host: redis
      port: 6379
