server:
  port: 8181

spring:
  application:
    name: api-gateway

management:
  endpoints:
    web:
      exposure:
        include: health, info, gateway
    endpoint:
      health:
        show-details: always
